# fly.toml app configuration file generated for bz-blog on 2023-11-02T15:55:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bz-blog"
primary_region = "iad"

[build]

[[mounts]]
  source = "pb_data"
  destination = "/pb/pb_data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
